# Generated by Django 5.0.6 on 2024-05-21 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_capacity_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
